# Generated by Django 3.1.14 on 2022-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='return_id',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
